[2023-03-17T03:11:50.893+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: FX_Reserves.extract scheduled__2023-02-25T00:00:00+00:00 [queued]>
[2023-03-17T03:11:50.907+0530] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: FX_Reserves.extract scheduled__2023-02-25T00:00:00+00:00 [queued]>
[2023-03-17T03:11:50.907+0530] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T03:11:50.907+0530] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-03-17T03:11:50.907+0530] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T03:11:50.930+0530] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract> on 2023-02-25 00:00:00+00:00
[2023-03-17T03:11:50.937+0530] {standard_task_runner.py:55} INFO - Started process 3270 to run task
[2023-03-17T03:11:50.940+0530] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'FX_Reserves', 'extract', 'scheduled__2023-02-25T00:00:00+00:00', '--job-id', '4838', '--raw', '--subdir', 'DAGS_FOLDER/FX_Reserves_Data.py', '--cfg-path', '/tmp/tmpry0m526o']
[2023-03-17T03:11:50.941+0530] {standard_task_runner.py:83} INFO - Job 4838: Subtask extract
[2023-03-17T03:11:51.103+0530] {task_command.py:389} INFO - Running <TaskInstance: FX_Reserves.extract scheduled__2023-02-25T00:00:00+00:00 [running]> on host DESKTOP-SQIOQPD.
[2023-03-17T03:11:51.295+0530] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nikheleshbhattacharyya@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=FX_Reserves
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-02-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-25T00:00:00+00:00
[2023-03-17T03:11:51.894+0530] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:1013 InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.rbi.org.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2023-03-17T03:11:51.944+0530] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/FX_Reserves_Data.py", line 43, in extract_fxres
    links = table.find_all('a',{"class": "link2"})
AttributeError: 'NoneType' object has no attribute 'find_all'
[2023-03-17T03:11:51.958+0530] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=FX_Reserves, task_id=extract, execution_date=20230225T000000, start_date=20230316T214150, end_date=20230316T214151
[2023-03-17T03:11:51.974+0530] {standard_task_runner.py:100} ERROR - Failed to execute job 4838 for task extract ('NoneType' object has no attribute 'find_all'; 3270)
[2023-03-17T03:11:51.997+0530] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-17T03:11:52.021+0530] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
